// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmPN065axE0PIw1sZNaeSqfPE2ioYrpiE',
    appId: '1:294684977510:web:e5d6f027ea9ca3c21280a7',
    messagingSenderId: '294684977510',
    projectId: 'next2watch-prod',
    authDomain: 'next2watch-prod.firebaseapp.com',
    storageBucket: 'next2watch-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWLG-GL24rA9CncS87QWMZ5ITGZB6dAPo',
    appId: '1:294684977510:android:9d394c8fd71105951280a7',
    messagingSenderId: '294684977510',
    projectId: 'next2watch-prod',
    storageBucket: 'next2watch-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnDJKuZb-twKPEWwvEHKLqofYWTu3lHPk',
    appId: '1:294684977510:ios:48a64ba26e7904851280a7',
    messagingSenderId: '294684977510',
    projectId: 'next2watch-prod',
    storageBucket: 'next2watch-prod.firebasestorage.app',
    iosBundleId: 'com.example.next2watch',
  );
}
